spring:
  application:
    name: emby_link
yang:
  emby:
    base-url: https://yy.codeyang.cn:82
    api-key: xxx
  alist:
    internal-base-url: xxx
    external-base-url: xxx
    api-key: xxx
  lan-ip: '192.168,10.110,fe80:'